const studentsData = [
  {
    id: 1,
    name: "Edriani, M.Pd",
    nickname: "Zah Eed",
    type: "teacher",
    role: "Wali Kelas X Sofia (2023/2024) & XI Latvia (2024/2025)",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Penyabar", "Pengayom", "Dedikatif"],
    hobby: "-",
    favFood: "-",
    favSong: "-",
    quote: "-",
    impression: "-",
    messageForClass: "-",
    futureHope: "-",
    futureSelfMessage: "-"
  },
  {
    id: 2,
    name: "Putri Handayani, S.Pd",
    nickname: "Zah Iput",
    type: "teacher",
    role: "Wali Kelas XII.4 Madrid (2025/2026)",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Perhatian", "Hangat", "Penyabar"],
    hobby: "-",
    favFood: "-",
    favSong: "-",
    quote: "Madrid zahhh, she is my girl, always.",
    impression: "Rusuh, heboh, gabisa diem kecuali saat tidur. Keliatan cuek dari luar, tapi hangat dari dalam.",
    messageForClass: "Jaga kesehatan ya girls, saat kuliah tu manajemen waktunya beda dari saat SMA. Minimal salat lima waktu ga tinggal, jilbab ga copot, tilawah jugaaa.",
    futureHope: "See u on top madrid, maybe 5 atau 10 tahun lagi kalau balik ke piar atau ketemu sazah dimanapun antuna tetep nyapa.",
    futureSelfMessage: "-"
  },
  {
    id: 3,
    name: "Afifah nurul izzah",
    nickname: "Ipeh",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1ABC123xyz_ID_FOTO_KAMU",
    traits: ["Manja", "Penyabar asekk", "Introvert"],
    hobby: "Dengerin lagu, nonton, baca buku",
    favFood: "Ayam",
    favSong: "Risk it all",
    quote: "Fall seven times, stand up eight.",
    impression: "Ngga kerasa bgt 3 thn di madrid dri awalnya ngga sedekat ituu dan pada akhirnya kita semua bisa sedekat itu banyak sii kenangan nya susah bgt buat di ceritainn apalagi pas kita sama sama berjuang untuk ujian ini ujian itu pokoknya best lah semua moment yg udh kita lalui ituu.",
    messageForClass: "Hai teman semua nya se mandrid cintaa semoga kita sukses selalu ya di kemudian harii dan juga semoga kita selalu mengingat satu sama lainn aku ngga ngingatin tentang istiqomah atau apapun itu tapi semoga kita bisa sadar sama tanggung jawab kita masing masing dan yang paling penting jangan tinggal sholat nya yaaa itu ajaa.",
    futureHope: "Sukses selalu madrid dunia dan akhiratnyaa semoga kita bisa jadi kebanggaan bagi diri kita sendiri dan orang lain.",
    futureSelfMessage: "hai aku dimasa depan semoga kamu bisa lebih sukses dan bisa banggain orng² disekitar kamu dan kamu bisa jdi yang lebih baik lagi dari diri kamu yang dulu, jangan lupa segala ibadah yang udah jadi landasan dan pondasi kamu sehingga kamu jadi orang yang seperti ini"
  },
  {
    id: 4,
    name: "Afifah Thohiroh muthmainnah",
    nickname: "ATM",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1NgxjFNAHc19nkeE1SqOoTcl-gbZic73x",
    traits: ["Ceria", "Baik", "Semangat"],
    hobby: "Jalan-jalan, baca novel",
    favFood: "Soto ayam, prata, ayam geprek",
    favSong: "Wavin' Flag, Kita Usahakan Rumah Itu, The Nights",
    quote: "Loving yourself is giving yourself what you want someone else to. Orang-orang besar itu terlahir dari masalah yang besar juga.",
    impression: "Aku seneng banget dapet orang orang madrid, karena dari walas yang support sampai kawan yang selalu ada, nonton sama sama, kena marah sama sama, asrama kelas 1 terpisah, tp itu yang bikin seru sama madrid, selalu dijalanin sama kerandomannya.",
    messageForClass: "Nikmati aja prosesnya kalau susah berhenti sebentar boleh kok tp jangan lama lama, lanjutkan lagi.",
    futureHope: "Sukses selalu ya madrid, jangan asing satu sama lain yaa.",
    futureSelfMessage: "1. Untk aku, Terima kasih ke diri sendiri karena udah berjuang sekeras ini sampai saat ini\n2. Untuk aku, usaha mu selama ini gak dia sia kok\n3. Untuk aku, apa yang kamu perjuangin selama ini, itu yang diinginkan kamu 15 tahun yang lalu\n4. Untuk aku, Aku gak nuntut kamu langsung sukses, nikmati aja prosesnya"
  },
  {
    id: 5,
    name: "aisyah azzahra fikria imam",
    nickname: "Icaza",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Excited", "Berani", "Frik aneh"],
    hobby: "Nyanyi, main FF, makan, baca",
    favFood: "Cokelat yang manis-manis",
    favSong: "Dash Uchiha",
    quote: "Kalo gabisa jadi orang baik, setidaknya jangan jadi orang jahat.",
    impression: "Selama 3 tahun tu.. astaga lucu bgt kita. Sering bcakak lah, pas kompak nya kompak bgt juga, tapi sumpah se seru itu bareng kalian semuaa.",
    messageForClass: "Pesan aku buat temen2 adalah sejauh apapun besok dunia luar membawa kita, jgn pernah lupa kalo kita prnah sedekat itu sama allah pas lagi susah kita pergi ke allah, pokoknya jgn trlalu jauh dehh dan kita hrs tetap saling mengingatkan yaa.",
    futureHope: "Semoga kita semua bisa jadi orang baik, jadi orang sukses, dan smoga kita ga pernah melupakan satu sama lainnnn juga saling mmbantuu.",
    futureSelfMessage: "10 tahun lagi aku udah jadi orang sukses AMIN, hrs tetap jdi org baik, ingat dulu di piar selalu diajarin, harus membantu yg kesusahan, ingat temen2 yg selalu bantuin, dan jgn prnah tinggalin allah"
  },
  {
    id: 6,
    name: "Alya malika wirahadi",
    nickname: "Malik",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Baik", "Cantik dan manis", "Penyayang & royal"],
    hobby: "Taktau",
    favFood: "Suka mie",
    favSong: "Banyak",
    quote: "Tetaplah menjadi dirimu, dan hargai orang yang menghargaimu dan tinggalkan orang yang menyepelekannmu.",
    impression: "Senangg bgt udh jdi bagian dri madrid, karna madrid udh sperti rumah dan keluarga kedua aku, pokokknyaa segala momen sama madrid takkan terlupakann, suksess utk madrid.",
    messageForClass: "Bagaimanapun dan dimanapun nanti kita berada semoga kita tak akan pernah lupa satu sama yang lain ya madridd, suksess untuk kita semua semoga kita sll dimudhkan jalan pintu kesuksesan ituu, semngaat madrid.",
    futureHope: "Semogaa kita menjadi manusia hebat dimasa depann nnti.",
    futureSelfMessage: "Tetap berjuang untuk masa depan, jalani segala takdir yg diberikan krna itu psti takdir terbaik yg disusun oleh tuhan, semngaat akuntan hebat"
  },
  {
    id: 7,
    name: "amaliya palupi hardian",
    nickname: "Amal",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Ngangenin", "Ngeselin", "Dramatic"],
    hobby: "Nonton",
    favFood: "Cheesecake",
    favSong: "Drop Dead / Wish List",
    quote: "Our future is up to us.",
    impression: "Segala hal ttg madrid berkesan bgttt. aku ga pandai berkata-kata tp madrid se membekas itu di hati akuuu tiga tahun pig berharga selama 17 taun aku hidupp., aku ga nyesel bgtt ngabisin masa sma aku bareng madridd, gaada hal yg ngga berkesan klo itu ttg madrid. sayang madrid banyak banyakk.",
    messageForClass: "Pokoknya madrid kerennn bgtt,, semoga kita bisa ketemu lagi di best version kita yahh i love my madridd so muchh.",
    futureHope: "I hope madrid sukseees dan tercapai smuwa wish listnyaa.",
    futureSelfMessage: "hem thank you for never giving up even when things got tough"
  },
  {
    id: 8,
    name: "Atikah Istiqamah",
    nickname: "Qomah",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Periang", "Cekatan", "Fleksibel"],
    hobby: "Basket, sepedaan",
    favFood: "Mie ayam",
    favSong: "The Said Only a Dignified Life",
    quote: "اللَّهُ مَعِي، اللَّهُ يَرَانِي، اللَّهُ شَاهِدِي (Allah bersamaku, Allah melihatku, Allah menyaksikanku).",
    impression: "Makan bajambaa, main basket sekelas sebelum project senam, waktu aku lagi sakit banyak yang care.",
    messageForClass: "Madrid sebelum melakukan apapun perbaiki niat kalian ya jangan sampai itu yang membuat kita jauh saat di akhirat dan semoga kita berjumpa di surga nantiii.",
    futureHope: "Semoga kitaa jadi orang sukseeeeeess (versi masing masing).",
    futureSelfMessage: "Qoom kamu sekarang udah ada perubahan kamu harus bisa banggain orang orang yang kamu sayang jangan lupa semua hasil kamu saat ini nggak luput pemberian dari allah jangn sampai kamu terlena oleh pencapaian kamu saat ini jadi aku berharap kamu bisaaa buat rumah hajiin ibu dan ayah dan bisa menjadi pemudi yang berguna bagi semua orang"
  },
  {
    id: 9,
    name: "Azkiah Mutia Najla",
    nickname: "Amoy",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1ABC123xyz_ID_FOTO_KAMU",
    traits: ["Lucu", "Imut", "Menggemaskan"],
    hobby: "Tidur, baca buku",
    favFood: "Bakso, kuaci",
    favSong: "Bayangkan Jika Kita Tidak Menyerah",
    quote: "Be happy not because everything is good, but you can see good in everything.",
    impression: "Madrid itu isinya orang orang yg punya mimpi mimpi besar dan mau memperjuangkan mimpi besar itu dan aku sangat bersyukur di kelilingi orang seperti itu.",
    messageForClass: "Untuk Madrid semoga suatu saat ketika kita bisa bertemu lagi, let's strive to be the best versions of our selves.",
    futureHope: "Harapan untuk Madrid semoga suatu saat kita bisa bertemu dan cerita kalo mimpi kita semua udah terwujud.",
    futureSelfMessage: "aku harap bisa menjadi versi terbaik dari diriku saat ini, semoga saat aku baca ini aku udah bisa wujudin cita cita yang selama ini aku usahakan ituu"
  },
  {
    id: 10,
    name: "CALLYSTA AURA AZ ZAHRA",
    nickname: "Celis",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1NgxjFNAHc19nkeE1SqOoTcl-gbZic73x",
    traits: ["Sabar", "Tidak sombong", "Cakep"],
    hobby: "Berenang",
    favFood: "Pempek",
    favSong: "Dandelions",
    quote: "QS. Al-Insyirah: 5-6",
    impression: "Asik bgt serius kek sksksk sangat amat kompak, anak”nya baik kerja sama mantap😖.",
    messageForClass: "Semoga bisa menempuh masa depan yg diimpikan.",
    futureHope: "Semoga madrid ga asing ya😍.",
    futureSelfMessage: "semoga jadi orang yg membanggakan"
  },
  {
    id: 11,
    name: "claudya annisa",
    nickname: "Kolok",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Gemoy lucu cimit", "Cerewet", "Selalu bahagia"],
    hobby: "Memasak, merakit lego",
    favFood: "Basreng, dendeng lambok",
    favSong: "Tarot, End of Beginning",
    quote: "Abandon thoughts that make you weak, and hold on to thoughts that give you strength.",
    impression: "Ak bangga puny tmn kls kyk madrid, karna pas dikala ak lagi down kemaren mereka selalu support ak. Hebohny madrid dikls sampe kita sering diblng 'ini ank ips ato ank ipa'. Kangen project dan keseruannya.",
    messageForClass: "Walaupun kita udh pada pisah/jauh tetapi ttp jgn asing ya guys🥹🥹.",
    futureHope: "Mudah”an kita sukses selalu di masa dpn ya guys dan mudah”an kita ga asing.",
    futureSelfMessage: "mendapatkan pekerjaan yg bagus utk bisa banggain kedua ortu ak..dan mendapatkan suami yg baik,soleh,pokony the best la"
  },
  {
    id: 12,
    name: "Diana Intan Putri",
    nickname: "Diana",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Alistabaa", "Suara emas", "Enjiner idaman"],
    hobby: "Main game, masak",
    favFood: "Martabak manis cokelat keju, bolu pisang",
    favSong: "Jatuh Suka, Lantas, Titik Nadir",
    quote: "Life is what happens to you while you're busy making other plans.",
    impression: "Aku happy jadi bagian madrid selama 3 tahun ini. Hehe makasi buat semuanya yang udah baaik bangeet. Ih gatau semuanya berkesan sekarang aku kangen banget ngumpul bareng.",
    messageForClass: "Buat teman' madrid aku yakin seyakin yakinnya kalau kita bakalan sukses di masa depan dengan jalan kita masing'🥺 semoga kalian selalu bahagia dengan apapun pencapaian yang kalian raih.",
    futureHope: "Sukses selalu madridku😘😘💜💜.",
    futureSelfMessage: "untuk aku di masa depan aku yakin banget kalau aku bisa sukses jadi apa yang aku impiin dari dulu, jadi apapun kmu nantinya jangan pernah kecewa dengan takdir yang kamu terima karna bahkan sejak sebelum kmu lahirpun hari itu sudah tertulis jangan pernah jadi sombong yaaa kalau suatu saat kamu jadi orang besar tetap rendah hati 😘"
  },
  {
    id: 13,
    name: "fadhilah zahrah",
    nickname: "Ara",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Public speaking", "Tegas", "Kepoan"],
    hobby: "Mendengarkan musik",
    favFood: "Dessert, ketoprak, siomay",
    favSong: "Lagu Sheila on 7 & Armada",
    quote: "You cry, you pray, you wait.",
    impression: "Semua yang terjadi dari kelas sofia sampai madrid ga ada yang ga berkesan, karna sama mereka semuanya jadi berkesan.",
    messageForClass: "Tetap saling mendoakan dan jaga tali silaturahmi.",
    futureHope: "Semoga kita semua mencapai impian terbaik kita.",
    futureSelfMessage: "untuk ara di umur 23-28 tahun semoga kamu sudah bekerja menjadi seorang yang hebat yang membanggakan orang tua dan orang sekitar,semoga kamu tetap istiqomah di jalan Allah swt,semoga kamu udah menikah dengan laki laki yang masyaallah akhlak,rupa,harta,hafalan,agama,dan hal baik lainnya"
  },
  {
    id: 14,
    name: "Fauzatul Husna",
    nickname: "Aza",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Rame", "Kreatif", "Unik"],
    hobby: "Membaca, menulis",
    favFood: "Cokelat",
    favSong: "Banyak",
    quote: "I survived every day I thought I couldn't. Maybe I'm not there yet, but I'm closer than I was yesterday.",
    impression: "Kalau Aza nggak pernah jadi bagian dari Madrid, kayaknya aku nggak bakal tahu kalau satu kelas bisa seseru ini. Madrid tuh isinya orang-orang yang rame, kreatif, unik, dan punya vibes masing-masing.",
    messageForClass: "Terima kasih untuk 3 tahun yang luar biasa ini.",
    futureHope: "Semoga mimpi-mimpi kita semua terwujud di masa depan.",
    futureSelfMessage: "Za, u finally survived!\nI'm so proud of u~\nHey, how are yahh?\nI hope u're doing okay.\nThe me writing this right now is dreaming of so many things, and I hope you didn't let her down.\n(╥﹏╥)\nNo matter what happened, I hope u never lost ur way.\nRemember, whenever things get hard, stay close to Allah. He's always been there for us.\nAnd hey, thank u for making it this far. I'm proud of u.\n(≧▽≦)🪷"
  },
  {
    id: 15,
    name: "haura ulya ramadhani",
    nickname: "Haura",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1ABC123xyz_ID_FOTO_KAMU",
    traits: ["Cantik", "Happy", "Sehat"],
    hobby: "Mendengarkan musik",
    favFood: "Makanan manis",
    favSong: "Banyak",
    quote: "Be a better version of yourself in the future.",
    impression: "Sangat bersyukur bisa tumbuh dan berjuang bersama anak-anak Madrid.",
    messageForClass: "buat semuwah tmn madrid akuu makasii buat semua kenangan dan pelajarannya😯aku ga bakal anggap kalian sbg orang asing di hidup aku and i hope you guys feel the same way😴🩷im soowrie buat all of my mistakes dan klo misalnya ada yg blm terbayarkan apapun itu BILANG AKU YAAH aku beruntung bgt pernah jd bagian dr kitaa😡⭐️aku bakal selalu berdoa kita ada di jalur terbaik yg udh disiapkan buat kita,see yuu on the besst top temen temenquu looovvyuuwh all with all haura’s heart🫆🩷",
    futureHope: "See you on top semuanya!",
    futureSelfMessage: "hiii hauraa di masa depan kamu gimana ok gaa apa ok bgttt?semoga yang kedua yeah.kamu masih cantik,happy,dan sehat kan?😯dari aku yang ada di juni 2024 hihi,jangan lupa sama yang udh kmu lewati,tetap semangat ngejalani hidup yang kamu punya gimanapun bentuk tantangannya,and you have to be proud of yourself coz u've passed so many obstacles nicely in your life,semangat buat hari esok,be a better version of yourself in the future,kamu tau kalo Allah bakal selalu ada disisi kamu kan?jangan lupa bersyukur yah,I know u can handle it all nicely!love u future hauraaa!mwah!🌷🫧🤍"
  },
  {
    id: 16,
    name: "Hilyah Qurota A'yun",
    nickname: "Hilya",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1NgxjFNAHc19nkeE1SqOoTcl-gbZic73x",
    traits: ["Penyabar", "Sopan", "Ceria"],
    hobby: "Membaca, menonton",
    favFood: "Makanan gurih",
    favSong: "Lagu-lagu santai",
    quote: "Tetap berusaha dan berdoa.",
    impression: "Banyak kenangan manis dan seru yang tak terlupakan.",
    messageForClass: "Jangan lupa untuk saling menyapa kalau ketemu.",
    futureHope: "Semoga kita semua sukses dunia dan akhirat.",
    futureSelfMessage: "semoga bahagia dan tentram selalu menjalani kehidupan, rezekinya berkah berlimpah, dan cita-citanya terwujud kabeh AAMIIINN."
  },
  {
    id: 17,
    name: "Nadhira Rajwa El Rafi",
    nickname: "Nadhira",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Ambisius", "Ceria", "Baik"],
    hobby: "Belajar, mendengarkan musik",
    favFood: "Bakso",
    favSong: "Pop",
    quote: "Jangan pernah menyerah sebelum mencoba.",
    impression: "Banyak si yaa, hampir semuanya gk bs aku lupain😭 tp kayak hujan” waktu rihlah, rayain ultah zah ed sm zah iput, bimbel bareng”, banyak deh😝",
    messageForClass: "Tetap semangat meraih impian masing-masing.",
    futureHope: "harapan nya semoga kalian bs sukses dan nikmatin kerja keras kalian selama ini dan bisa jadi orang” keren kebanggan semua🤩",
    futureSelfMessage: "Hai nad? kira” sekarang kmu lagi ngapain ya? Hehe😋 kamu pasti udh gapai mimpi mu itu kan? aku harap kmu senang tanpa mikirin apa pun lagi, trus jangan lupa ya perjuangan kmu bertahun tahun yg lalu ( btw kmu jd masuk ugm gk? Hehe🤧) klu aku mau di unand dlus😉"
  },
  {
    id: 18,
    name: "Nafisah Faiza farhani",
    nickname: "Picah",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Mandiri", "Tekun", "Ramah"],
    hobby: "Membaca",
    favFood: "Makanan pedas",
    favSong: "Banyak",
    quote: "Kerja keras tidak akan mengkhianati hasil.",
    impression: "Masa-masa SMA bersama Madrid adalah momen terbaik.",
    messageForClass: "Semoga kita semua menjadi orang yang sukses.",
    futureHope: "Tetap solid dan saling menjaga hubungan baik.",
    futureSelfMessage: "semoga cita citaku di masa depan tercapai,menjadi wanita karir dan sukses"
  },
  {
    id: 19,
    name: "Naurah Amalia Syahidah",
    nickname: "K'nau",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Pemalu", "Soft spoken", "Luchuu"],
    hobby: "Banyak pokoknya",
    favFood: "Keju, manis-manis, tidak pedas",
    favSong: "Banyak pokoknya",
    quote: "Be kind, be grateful, and trust Allah's timing. 🤍",
    impression: "Pokoknya semua keseruan dan cerita di madrid apa lagi liat sifat random kalian.",
    messageForClass: "Terima kasih untuk semua teman-teman yang sudah menjadi bagian dari perjalanan ini. Semoga kita semua diberikan kesehatan, kebahagiaan, dan kesuksesan dalam meraih cita-cita. Jangan lupakan kenangan yang telah kita buat bersama ya, Semoga persahabatan dan silaturahmi kita tetap terjaga walaupun nanti berada...",
    futureHope: "Sukses selalu untuk kita semua.",
    futureSelfMessage: "untuk nau dimasa depan semoga kamu bisa menggapai impian mu dan selalu jadi diri sendiri serta jgn lupa bahagiakan ortu mu"
  },
  {
    id: 20,
    name: "Nawal Husna Mufida",
    nickname: "Nawal",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Penyabar", "Baik", "Perhatian"],
    hobby: "Membaca",
    favFood: "Ayam goreng",
    favSong: "Lagu santai",
    quote: "Lakukan yang terbaik dalam setiap kesempatan.",
    impression: "Setiap hari di kelas Madrid selalu ada hal lucu dan berkesan.",
    messageForClass: "Jangan lupa untuk selalu bersyukur dan menjaga ibadah.",
    futureHope: "Semoga sukses di jalan masing-masing.",
    futureSelfMessage: "hai nawall dimasa depan, semoga kamu sudah berhasil menggapai impian kamu, menjadi anak yang membanggakan bagi ortu kamu, bahagiakan ortu kamu selagi kamu mampu, kamu hebat udah bisa lewati masa-masa sulit pas sma dulu, pertahankan ibadah kamu walau sesibuk apapun kamu di masa depan, jangan lupa bersyukur, love u yaww 💗💗"
  },
  {
    id: 21,
    name: "Nur Aqila",
    nickname: "Aqila",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1ABC123xyz_ID_FOTO_KAMU",
    traits: ["Ceria", "Aktif", "Kreatif"],
    hobby: "Olahraga, mendengarkan musik",
    favFood: "Mie",
    favSong: "Pop",
    quote: "Jalani hari dengan senyuman.",
    impression: "Kebersamaan dengan Madrid bikin kangen terus.",
    messageForClass: "Semoga cita-cita kita semua terkabul.",
    futureHope: "Tetap ingat kenangan indah di SMA.",
    futureSelfMessage: "muda, kaya raya, mati masuk surga"
  },
  {
    id: 22,
    name: "Nur Azizah",
    nickname: "Ajo",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1NgxjFNAHc19nkeE1SqOoTcl-gbZic73x",
    traits: ["Gigih", "Pantang menyerah", "Baik"],
    hobby: "Belajar, membaca",
    favFood: "Nasi goreng",
    favSong: "Lagu motivasi",
    quote: "Jangan pantang menyerah dan terus berjuang.",
    impression: "Bertumbuh bareng-bareng dikelas tercinta.",
    messageForClass: "untuk madrid kalian jangan lupa sama teman teman berjuang masa sma ya trss semoga apa yang kalian perjuangin sekarang ada hasil di masa depan yaakk",
    futureHope: "Semoga semua impian anak Madrid terwujud.",
    futureSelfMessage: "jangan pantang menyerah dan terus berjuang berusaha selalu"
  },
  {
    id: 23,
    name: "Nur Azizahh",
    nickname: "Ajonk",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Cerewet 😬", "Ngambekan dan manja 😬", "Suaranya cempreng 😬"],
    hobby: "Membaca, ak suka masak walaupun gosong and ga enak🙂",
    favFood: "Serba chiki",
    favSong: "Bergema sampai selamanya🌷",
    quote: "Duh hmm apa yahh.....ga suka kata' suka nya bukti nyata",
    impression: "Madrid isinya orang spesial semuaa,kerandoman Madrid bikin gamon bgtt ,suka bgtt isengnya reva dikelas,kngen cecel dgn 1000 tingkah dan pertanyaannya,duh bnykk lgi dehhh...pokoknya Madrid bikin gamon beratt😭",
    messageForClass: "semoga anak madrid sukses terus,sehat'terus,jgn lupain kita pernah bareng 3thn melawan kejenuhan di piar",
    futureHope: "nnti kedepannya kita dah dalam perjuangan kita masing' jangan sampai asing yah",
    futureSelfMessage: "semogaa aku lebih baik lagi kedepannya,apapun perjuangan yg dilakukan semoga allah mudahkan dan semoga ak jdi org baik dan sukses kedepannya"
  },
  {
    id: 24,
    name: "Nurul Najmi A'isyah",
    nickname: "Nuna",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Matematika", "Dance", "Novel"],
    hobby: "Dance, baca buku",
    favFood: "Mochi dan jamur enoki",
    favSong: "Shout Out dan Joyride",
    quote: "Dan jika ia datang kepada-Ku dengan berjalan, Aku akan datang kepadanya dengan berlari.",
    impression: "Salah satu yg lumayan berkesan buat aku terkhususnya waktu udah kelas tiga adalah waktu ngerayain ulang tahunnya zah iput♡ karena hadiah nya tuh bener bener random dan seru banget.",
    messageForClass: "Keep fighting teman teman semua, perjalanan kita masih jauh, langkah kita boleh beda tapi kenangan kita bakal tetap sama. Sampai jumpa di puncak kesuksesan dan versi terbaik diri kita masing-masing.",
    futureHope: "Sukses untuk kita semua di masa depan.",
    futureSelfMessage: "hai nuna dimasa depan, kalo kamu udah baca ini kamu hebat ya udah bertahan sejauh ini, apapun pencapaian kamu sekarang aku bangga sama kamu. Terus menebar kebaikan ya na! Dan jangan lupa kalau kamu pny Allah yang bakal bantu kamu disaat kamu merasa ga sanggup lagi."
  },
  {
    id: 25,
    name: "Puteri Caya Maharani",
    nickname: "Cya",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Setia kawan", "Baik", "Manis"],
    hobby: "Mendengarkan musik",
    favFood: "Cemilan",
    favSong: "Pop",
    quote: "Gapapa terlambat, dari pada tidak sama sekali.",
    impression: "Meskipun sempat pindah sekolah, kenangan bersama teman-teman Madrid tetap paling berkesan.",
    messageForClass: "Tetap jadi teman yang saling mendukung.",
    futureHope: "Semoga Madrid makin sukses.",
    futureSelfMessage: "gapapa terlambat, dari pada tidak sama sekali"
  },
  {
    id: 26,
    name: "Reva Marlina",
    nickname: "Reva",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Iseng", "Ceria", "Heboh"],
    hobby: "Bercanda, nonton",
    favFood: "Ayam goreng",
    favSong: "Lagu rame",
    quote: "Hidup dibawa santai tapi tetap berjuang.",
    impression: "Banyak banget momen kocak dan rusuh di kelas.",
    messageForClass: "Jangan lupa sama kerandoman kita.",
    futureHope: "Semoga kita semua sukses bareng-bareng.",
    futureSelfMessage: "untuk reva masa depan..semoga kamu sudah menjadi orang yang sukses dan lebih berguna lagi bagi org disekitarmu.makasih udah berjuang sejauh ini dan jangan pantang menyerah...ilysm💗"
  },
  {
    id: 27,
    name: "Rifa Ayuni Putri Dinata",
    nickname: "Ipak",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1ABC123xyz_ID_FOTO_KAMU",
    traits: ["Lucu lucu", "Penyayang", "Sopan"],
    hobby: "NONTONNN,,",
    favFood: "Ayam geprek, dimas mentai my loafff🤤, semua pisangpisangan.",
    favSong: "NOTHINGG LAST FOREVER - MAROON 5",
    quote: "Love smiling love laughing.",
    impression: "1. WAKTU TBC WOII 2. MUSIM LONGSOR BANJIR BANDANG HAHAH 3. DI SOFIA NONTON TERUSSS.",
    messageForClass: "madrid selalu kerennnn🤩🥹so glad to know them.",
    futureHope: "dimanapun semuanya semoga selalu sukses.",
    futureSelfMessage: "ingat lah dari mana asal mu, berterimakasih lah kepada org\" yang ada disamping mu saat kmu berada di bawah, jangan pernah sombong ketika berada di atas, dan tetap lah menjadi orang yang rendah hati"
  },
  {
    id: 28,
    name: "sabita izzati aqila",
    nickname: "Bita",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1NgxjFNAHc19nkeE1SqOoTcl-gbZic73x",
    traits: ["Ketua angkatan", "Perhatian", "Penyabar"],
    hobby: "Membaca, belajar",
    favFood: "Makanan sehat",
    favSong: "Lagu bermakna",
    quote: "Semua yang tertakar tidak akan tertukar.",
    impression: "teman teman cu tersayang… makasi yaa udh menemani hari hari selama di piar🥺💕🥺💕 mau senang apa sedih itu semua jadi cerita buat kita.. maafin aku yg masih banyak salahnya yaa… maafin aku kalo bikin kalian kesal… belum bisa jadi yg lebih baik😓😓 jujur aku baru berasa sedihnya pas ngetik ini.. soalnya kemaren” rasanya kita ga bener bener berpisah… setiap kalian punya cerita indah di dalam hati aku.. semuanya berkesan di aku.. mungkin kalian lupa tapi aku ingat ataupun kebalikannya… maafin aku ya sebagai ketua angkatan masi belum bisa memberi contoh yg baik… sering buat kalian kesal juga… sering marah marah juga.. maafinn bgttt yahh😓 😓 dan ingat yah teman teman.. semua yg tertakar tidak akan tertukar, kalo udh usaha maksimal n belum dapat yg terbaik, mungkin embg...",
    messageForClass: "Tetap semangat dan senantiasa mendekatkan diri kepada Allah.",
    futureHope: "Semoga semua anggota Madrid mencapai cita-citanya.",
    futureSelfMessage: "semoga cita cita bita bisa tercapai,bita jadi org sukses,dikelilingi orang baik,jaga sholat nya,selalu dekat sm Allah,bahagiain orang tua,bisa meluaskan ilmu pengetahuan bita,bermanfaat bagi banyak orang,selalu dilindungi Allah,AAMIIN🤲🏻"
  },
  {
    id: 29,
    name: "Syifa Az-zahra",
    nickname: "Syitoh",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Sabar", "Ga pendendam", "Suka menolong"],
    hobby: "Membaca, membantu teman",
    favFood: "Makanan favorit sekelas",
    favSong: "Lagu syahdu",
    quote: "Selalu melibatkan Allah dalam segala hal.",
    impression: "Momen kebersamaan pas malam-malam dan perjuangan kelas.",
    messageForClass: "Tetap jadi orang baik dan jangan pernah tinggalkan sholat.",
    futureHope: "Semoga kita semua berada di jalan yang diridhoi Allah.",
    futureSelfMessage: "halo syitoh dimasa depan.. makasi ya udah bertahan sampai saat ini, proud of u so much.. tetap jadi syitoh yang sabar, ga pendendam, dan suka menolong yaa.. aku ga nuntut kamu harus jadi apa nantinya, yang penting kamu selalu melibatkan Allah dalam segala hal, selalu berada di jalannya Allah, dan terhindar dari maksiat.. dimanapun kamu berada tolong jgn pernah tinggalkan sholat ya.. syitoh kamu keren bgt, lopek u pulll💗💗"
  },
  {
    id: 30,
    name: "Syifa Latifah",
    nickname: "Cipa",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Bersyukur", "Ramah", "Baik"],
    hobby: "Mendengarkan musik",
    favFood: "Cemilan enak",
    favSong: "Pop",
    quote: "Selalu bersyukur atas segala nikmat.",
    impression: "Masa SMA penuh warna dan kegembiraan bareng Madrid.",
    messageForClass: "Semoga sukses selalu teman-teman.",
    futureHope: "Semoga cita-cita kita tercapai.",
    futureSelfMessage: "semoga kelak cipa impiannya tercapai dan ga lupa utk bersyukur"
  },
  {
    id: 31,
    name: "Zakiah Salsabila",
    nickname: "Kiaa",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Religius", "Baik", "Penyabar"],
    hobby: "Membaca",
    favFood: "Makanan rumahan",
    favSong: "Lagu bernuansa islami/santai",
    quote: "Jaga sholat dimanapun berada.",
    impression: "Sangat bersyukur dapat sekelas dengan orang-orang baik di Madrid.",
    messageForClass: "kiaa jangan pernah lupa sm Allah yaa, penting dimanapun tetap jaga sholatnya ya.",
    futureHope: "Tetap keep in touch semuanya, sukses di pilihan masing-masing.",
    futureSelfMessage: "kiaa jangan pernah lupa sm Allah yaa, penting dimanapun tetap jaga sholatnya ya."
  },
  {
    id: 32,
    name: "Zaskia Irna Dewantari",
    nickname: "Berbi",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Cinta damai", "Easy going", "Ramah"],
    hobby: "Menyanyi",
    favFood: "Satai",
    favSong: "Shape of My Heart",
    quote: "The beautiful thing about life is that you can always change and grow.",
    impression: "Bisa sekelas dengan orang-orang random, pinter, dan ambis kayak kalian.",
    messageForClass: "Tetap jadi diri sendiri ya guys, jangan lupakan kebersamaan kita.",
    futureHope: "Harapannya semoga kita semua bisa sukses menggapai masa depan.",
    futureSelfMessage: "tetap rendah hati, tidak tinggi hati, jadilah versi terbaik dari dirimu"
  },
  {
    id: 33,
    name: "Zikra Aridiastuti",
    nickname: "Zizi",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Girly", "Mungil", "Cantik"],
    hobby: "Membaca novel, melukis, shopping",
    favFood: "Pie cheese, brownies, telur gulung",
    favSong: "Thank u, next / I Think I Like You Better When You're Gone / Adu Rayu",
    quote: "Be proud of yourself because you have survived a lot of things no one even noticed 🌟",
    impression: "seruny nobar sekelas diem” dan byk drama,out of the box bgt keseharianny,bner” isiny cegil😭",
    messageForClass: "untuk semuany,mgkin kalian inget di 17 agustus kmrn kita pernah bkin vidio ngucapin harapan buat sesama kita semoga apapun yg kalian ucapin hari itu dan dividio itu bner” bisa tercapai ya teman” ku😕💗💗 kata” terbaik untuk kalian semua😕",
    futureHope: "Semoga sukses menggapai cita-cita semuanya.",
    futureSelfMessage: "dimn zizi berada tlg tetep jaga sholatny ya,jaga amalan” ibadah ny,jd org baik ya zi ke siapapun,ttep pelajari hal” baru,ttp jd zizi yg ga gampang baperan,semoga cita” zizi secepetny bisa dpt restu dr mama papa biar bs di wujudin secepetny jg,semoga zizi secepetny dpt pekerjaan yg bagus&dikelilingi org” baik,jd org sukses,bisa beli rumah sendiri,bisa naik haji secepat ny,punya tabungan byk🥹"
  }
];
