const madridData = [
  {
    id: 1,
    name: "Edriani, M.Pd",
    nickname: "Zah Eed",
    role: "Wali Kelas (2023/2024 & 2024/2025)",
    image: "1.jpg",
    traits: ["Wali Kelas 😘👩‍🏫", "Penyayang 💖", "Pengayom 🛡️"],
    hobbies: "-",
    favoriteFood: "-",
    favoriteSong: "-",
    quote: "-",
    messageToFriends: "-",
    hopeForClass: "-",
    messageToSelf: "-"
  },
  {
    id: 2,
    name: "Putri Handayani, S.Pd",
    nickname: "Zah Iput",
    role: "Wali Kelas (2025/2026)",
    image: "2.jpg",
    traits: ["Penyayang🌷", "Heboh 🎉", "Hangat 🥰"],
    hobbies: "-",
    favoriteFood: "-",
    favoriteSong: "-",
    quote: "🤍",
    messageToFriends: "Jaga kesehatan ya girls, Saat kuliah tu, manajemen waktunya beda dari saat SMA, gatau kenapa kekurangan waktu muluuu. Minimal salat lima waktu ga tinggal, jilbab ga copot, tilawah jugaaa. Trus kalau ke piar, pliss masuk kantor guru salami tu guru satu2, I really2 proud if u come tu my office, pas salim ama guru lain ditanya kelas mana dlu ? Sopan bener. So i can say : madrid zahhh, she is my girl, always. Bangga bener aslii",
    hopeForClass: "See u on top madrid, Maube 5 atau 10 tahun lagi kalau balik ke piar atau ketemu sazah dimanapun antuna tetep nyapa, Trus cerita kisah hidupnya gimana. Eitss, sga harus kisah senengnya aja yaaa. Sazah lebihh berharap kalau antuna terpuruk, sedih, merasa stuck, sazah masih menjadi salah satu orang yg dicari buat cerita.🥰🥹🫂",
    messageToSelf: "-"
  },
  {
    id: 3,
    name: "Afifah Nurul Izzah",
    nickname: "Ipeh",
    role: "Siswi Madrid",
    image: "3.jpg",
    traits: ["Manja 🥺", "Penyabar 🕊️", "Introvert 🤫"],
    hobbies: "Dengerin lagu 🎧, nonton 🎬, baca buku 📚",
    favoriteFood: "Ayam 🍗",
    favoriteSong: "Risk It All 🎶",
    quote: "Fall seven times, stand up eight. 💪🏻✨",
    messageToFriends: "hai teman semua nya se mandrid cintaa semoga kita sukses selalu ya di kemudian harii dan juga semoga kita selalu mengingat satu sama lainn aku ngga ngingatin tentang istiqomah atau apapun itu tapi semoga kita bisa sadar sama tanggung jawab kita masing masing dan yang paling penting jangan tinggal sholat nya yaaa itu ajaa. 🤲🏻🤍",
    hopeForClass: "Sukses selalu madrid dunia dan akhiratnyaa semoga kita bisa jadi kebanggaan bagi diri kita sendiri dan orang lain. 🌟💖",
    messageToSelf: "hai aku dimasa depan semoga kamu bisa lebih sukses dan bisa banggain orng² disekitar kamu dan kamu bisa jdi yang lebih baik lagi dari diri kamu yang dulu,jangan lupa segala ibadah yang udah jadi landasan dan pondasi kamu sehingga kamu jadi orang yang seperti ini.🥺🎓"
  },
  {
    id: 4,
    name: "Afifah Thohiroh Muthmainnah",
    nickname: "ATM",
    role: "Siswi Madrid",
    image: "4.jpg",
    traits: ["Ceria ☀️", "Baik 💖"],
    hobbies: "Jalan-jalan 🚗, baca novel 📖",
    favoriteFood: "Soto ayam 🥣, prata 🫓, ayam geprek 🍗",
    favoriteSong: "Wavin Flag 🚩, Kita Usahakan Rumah Itu 🏠, Avicii - The Nights 🎧",
    quote: "Loving yourself is giving yourself what you want someone else to. 💌",
    messageToFriends: "Aku seneng banget dapet orang orang madrid, karena dari walas yang support sampai kawan yang selalu ada, nonton sama sama, kena marah sama sama, asrama kelas 1 terpisah, tp itu yang bikin seru sama madrid, selalu dijalanin sama kerandomannya.🥺🫂",
    hopeForClass: "sukses selalu ya madrid, jangan asing satu sama lain yaa, nikmati aja prosesnya kalau susah berhenti sebentar boleh kok tp jangan lama lama, lanjutkan lagi. 💖💫",
    messageToSelf: "1. Untk aku, Terima kasih ke diri sendiri karena udah berjuang sekeras ini sampai saat ini. 2. Untuk aku, usaha mu selama ini gak dia sia kok. 3. Untuk aku, apa yang kamu perjuangin selama ini, itu yang diinginkan kamu 15 tahun yang lalu . 4. Untuk aku, Aku gak nuntut kamu langsung sukses, nikmati aja prosesnya.🥺👏🏻"
  },
  {
    id: 5,
    name: "Aisyah Azzahra Fikria Imam",
    nickname: "Icaza",
    role: "Siswi Madrid",
    image: "5.jpg",
    traits: ["Excited 🔥", "Berani 🦁", "Frik aneh 👾"],
    hobbies: "Nyanyi 🎤, main FF 🎮, makan 🍿, baca 📚",
    favoriteFood: "Cokelat yang manis-manis 🍫",
    favoriteSong: "Dash Uchiha 🎶",
    quote: "Kalo gabisa jadi orang baik, setidaknya jangan jadi orang jahat. 🕊️✨",
    messageToFriends: "pesan aku buat temen2 adalah sejauh apapun besok dunia luar membawa kita, jgn pernah lupa kalo kita prnah sedekat itu sama allah😆pas lagi susah kita pergi ke allah, pokoknya jgn trlalu jauh dehh😞💔 dan kita hrs tetap saling mengingatkan yaa😆🤤🫰🏻🥺💖",
    hopeForClass: "semoga kita semua bisa jadi orang baik, jadi orang sukses, dan smoga kita ga pernah melupakan satu sama lainnnn juga saling mmbantuu😆🫰🏻💗🫂🌟",
    messageToSelf: "10 tahun lagi aku udah jadi orang sukses AMIN,    hrs tetap jdi org baik, ingat dulu di piar selalu diajarin, harus membantu yg kesusahan, ingat temen2 yg selalu bantuin, dan jgn prnah tinggalin allah😋😆🫰🏻🤲🏻🤍"
  },
  {
    id: 6,
    name: "Alya Malika Wirahadi",
    nickname: "Malik",
    role: "Siswi Madrid",
    image: "6.jpg",
    traits: ["Cantik & Manis 🌸", "Penyayang 💖", "Softspoken 🕊️"],
    hobbies: "Taktau 🤷🏻‍♀️",
    favoriteFood: "Sesuai mood tapi sangat suka mie 🍜",
    favoriteSong: "Banyak 🎵",
    quote: "Tetaplah menjadi dirimu, dan hargai orang yang menghargaimu. ✨🤍",
    messageToFriends: "Bagaimanapun dan dimanapun nanti kita berada semoga kita tak akan pernah lupa satu sama yang lain ya madridd, suksess untuk kita semua semoga kita sll dimudhkan jalan pintu kesuksesan ituu,semngaat madrid🫶🏻🫶🏻🥺🥺🥹🤝🏻",
    hopeForClass: "Senangg bgt udh jdi bagian dri madrid,karna madrid udh sperti rumah dan keluarga kedua aku,pokokknyaa segala momen sama madrid takkan terlupakann,suksess utk madrid🫶🏻🫶🏻. Semogaa kita menjadi manusia hebat dimasa depann nnti🌟👑",
    messageToSelf: "Tetap berjuang untuk masa depan,jalani segala takdir yg diberikan krna itu psti takdir terbaik yg disusun oleh tuhan, semngaat akuntan hebat🫶🏻🫵🏻🤲🏻🤍"
  },
  {
    id: 7,
    name: "Amaliya Palupi Hardian",
    nickname: "Amal",
    role: "Siswi Madrid",
    image: "7.jpg",
    traits: ["Ngangenin 🥺", "Ngeselin 😜", "Dramatic 🎭"],
    hobbies: "Nonton 🍿",
    favoriteFood: "Cheesecake 🍰",
    favoriteSong: "Drop Dead / Wish List 🎶",
    quote: "Our future is up to us - Enola Holmes 🕵🏻‍♀️✨",
    messageToFriends: "“segala hal ttg madrid berkesan bgttt💗,,aku ga pandai berkata-kata tp madrid se membekas itu di hati akuuu😖😵‍💫,,tiga tahun plg berharga selama 17 taun aku hidupp,,aku ga nyesel bgtt ngabisin masa sma aku bareng madridd,,gaada hal yg ngga berkesan klo itu ttg madrid🥺sayang madrid banyak banyakk😘💗😖pokoknya madrid kerennn bgtt,,semoga kita bisa ketemu lagi di best version kita yahh🥹💖",
    hopeForClass: "I hope madrid sukses dan tercapai semua wish listnya. 🌟📜",
    messageToSelf: "Thank you for never giving up even when things got tough. 🫂🤍"
  },
  {
    id: 8,
    name: "Atikah Istiqamah",
    nickname: "Qomah",
    role: "Siswi Madrid",
    image: "8.jpg",
    traits: ["Periang ⚡", "Cekatan 🏃🏻‍♀️", "Fleksibel 🧘🏻‍♀️"],
    hobbies: "Basket 🏀, sepedaan 🚲",
    favoriteFood: "Mie ayam 🍜",
    favoriteSong: "They Said Only A Dignified Life 🎶",
    quote: "اللَّهُ مَعِي، اللَّهُ يَرَانِي، اللَّهُ شَاهِدِي Allah bersamaku, Allah melihatku, Allah menyaksikanku 🤲🏻🤍",
    messageToFriends: "Madrid sebelum melakukan apapun perbaiki niat kalian ya jangan sampai itu yang membuat kita jauh saat di akhirat dan semoga  kita berjumpa di surga nantiii. 💡✨",
    hopeForClass: "Semoga kita jadi orang sukses (versi masing-masing). 🎓🌟",
    messageToSelf: "Qoom kamu sekarang udah ada perubahan kamu harus bisa banggain orang orang yang kamu sayang jangan lupa semua  hasil kamu saat ini nggak luput pemberian dari allah jangn sampai kamu terlena oleh pencapaian kamu saat ini jadi aku berharap kamu bisaaa buat rumah hajiin ibu dan ayah dan bisa menjadi pemudi yang berguna bagi semua orang. 🥺🕋🤍"
  },
  {
    id: 9,
    name: "Azkiah Mutia Najla",
    nickname: "Amoy",
    role: "Siswi Madrid",
    image: "9.jpg",
    traits: ["Lucu 😆", "Imut 🤏🏻", "Menggemaskan 🥺"],
    hobbies: "Tidur 😴, baca buku 📚",
    favoriteFood: "Bakso 🥣, kuaci 🌻",
    favoriteSong: "Bayangkan Jika Kita Tidak Menyerah - Hindia 🎧",
    quote: "Be happy not because everything is good but you can see good in everything. 🌈✨",
    messageToFriends: "Untuk Madrid semoga suatu saat ketika kita bisa bertemu lagi, let's strive to be the best versions of our selves. 💖🚀",
    hopeForClass: "Madrid itu isinya orang orang yg punya mimpi mimpi besar dan mau memperjuangkan mimpi besar itu dan aku sangat bersyukur di kelilingi orang seperti itu. Semoga suatu saat kita bisa bertemu dan cerita kalo mimpi kita semua udah terwujud. 🥺🥂✨",
    messageToSelf: "Aku harap bisa menjadi versi terbaik dari diriku saat ini. 🌱🤍"
  },
  {
    id: 10,
    name: "Callysta Aura Az Zahra",
    nickname: "Celis",
    role: "Siswi Madrid",
    image: "10.jpg",
    traits: ["Sabar 🕊️", "Tidak sombong 🤍", "Cakep ✨"],
    hobbies: "Swimming 🏊🏻‍♀️",
    favoriteFood: "Pempek 🐟",
    favoriteSong: "Dandelions 🌼",
    quote: "Al-Insyirah 5-6 📖🤍",
    messageToFriends: "Semoga bisa menempuh masa depan yang diimpikan. 🎓🌟",
    hopeForClass: "Asik bgt serius kek sksksk sangat amat kompak, anak2nya baik kerja sama mantap😖🫰🏻Semoga madrid gak asing ya. 🥹🤝🏻",
    messageToSelf: "Semoga jadi orang yang membanggakan. 🥺👑"
  },
  {
    id: 11,
    name: "Claudya Annisa",
    nickname: "Kolok",
    role: "Siswi Madrid",
    image: "11.jpg",
    traits: ["Gemoy 🧸", "Cerewet 🗣️", "Selalu bahagia 🥳"],
    hobbies: "Memasak 🧑🏻‍🍳, merakit lego 🧩",
    favoriteFood: "Basreng 🧆, dendeng lambok 🥩",
    favoriteSong: "Tarot 🃏, End of Beginning 🎶",
    quote: "Abandon thoughts that make you weak, and hold on to thoughts that give you strength. 💪🏻✨",
    messageToFriends: "•ak bangga puny tmn kls kyk madrid,karna pas dikala ak lagi down kemaren mereka selalu support ak🫶🏻 •hebohny madrid dikls sampe kita sering diblng “ini ank ips ato ank ipa” •kangen project dan keseruannyaWalaupun kita udah pada pisah/jauh tetapi tetap jangan asing ya guys. 🥺🫂",
    hopeForClass: "Mudah-mudahan kita sukses selalu di masa depan dan gak asing. 🌟💖",
    messageToSelf: "Mendapatkan pekerjaan yg bagus utk bisa banggain kedua ortu ak..dan mendapatkan suami yg baik,soleh,pokony the best la. 💼🎓"
  },
  {
    id: 12,
    name: "Diana Intan Putri",
    nickname: "Diana",
    role: "Siswi Madrid",
    image: "12.jpg",
    traits: ["Alistaba ✨", "Suara emas 🎙️", "Enjiner idaman ⚙️"],
    hobbies: "Main game 🎮, masak 🍳",
    favoriteFood: "Martabak manis coklat keju 🍫🧀, bolu pisang 🍌",
    favoriteSong: "Jatuh Suka, Lantas - Juicy Luicy 🎵",
    quote: "Life is what happens to you while you are busy making other plans. 🍃",
    messageToFriends: "Semoga kalian selalu bahagia dengan apapun pencapaian yang kalian raih. 💖🎉",
    hopeForClass: "Sukses selalu madridku! 🚀🥳",
    messageToSelf: "Jangan pernah kecewa dengan takdir yang kamu terima. Tetap rendah hati. 🤲🏻🤍"
  },
  {
    id: 13,
    name: "Fadhilah Zahrah",
    nickname: "Ara",
    role: "Siswi Madrid",
    image: "13.jpg",
    traits: ["Public speaking 🎙️", "Tegas ⚡", "Kepoan 🧐"],
    hobbies: "Listen to music 🎧",
    favoriteFood: "Desserts 🍰, perkuah kacang-kacangan (ketoprak, siomay) 🍲",
    favoriteSong: "Lagu-lagu SO7 & Armada 🎸",
    quote: "You cry, you pray, you wait. 🥺🤲🏻",
    messageToFriends: "Tolong ingat Ara yang baiknya aja ya teman-teman, Ara beruntung kenal kalian. 🥺🤍",
    hopeForClass: "Semoga kalian diberikan kebahagiaan, kesuksesan, dan hal baik lainnya. 🌟🌈",
    messageToSelf: "Semoga kamu sudah bekerja menjadi seorang yang hebat yang membanggakan orang tua. 🎓💼"
  },
  {
    id: 14,
    name: "Fauzatul Husna",
    nickname: "Aza",
    role: "Siswi Madrid",
    image: "14.jpg",
    traits: ["Ekspresif 🎭", "Perasa 🥺", "Fleksibel 🍃"],
    hobbies: "Seni (menggambar 🎨, musik 🎶), refleksi diri 🧘🏻‍♀️, manhwa 📖",
    favoriteFood: "Peraci-acian 🍡, soup 🥣, chicken katsu 🍛, cheesecake 🍰",
    favoriteSong: "The Cutest Pair 🎶, Bunga Abadi 🌸, Bubble Gum - NewJeans 🫧",
    quote: "I survived every day I thought I could not. Maybe I am not there yet, but I am closer than I was yesterday. 🌱✨",
    messageToFriends: "Makasih buat 3 tahun yang penuh cerita. Jangan lupa jaga diri dan tetap istiqomah. 🥹🤲🏻",
    hopeForClass: "Jangan pernah lupa kalau kita pernah berada di masa perjuangan yang sama. See you in a better place! 🫂💖",
    messageToSelf: "Za, u finally survived! No matter what happened, I hope u never lost ur way. 🤍🫂"
  },
  {
    id: 15,
    name: "Haura Ulya Ramadhani",
    nickname: "Haura",
    role: "Siswi Madrid",
    image: "15.jpg",
    traits: ["Suka warna-warni 🌈", "Girly 👗", "Cute 🤏🏻"],
    hobbies: "Nyanyi 🎤, jalan-jalan 🛍️, jajan 🧋",
    favoriteFood: "Suka semuanya 😋",
    favoriteSong: "Saving All My Love for You 🎶, Officially Missing You 🎸",
    quote: "See beauty in everything, lessons in every hardship. 🌸✨",
    messageToFriends: "Aku ga bakal anggap kalian sbg orang asing di hidup aku. Love u all with all Haura heart! 🥹💖",
    hopeForClass: "Semoga kita bisa bersyukur dan bangga sama capaian kita yang udah diusahakan. 🌟🥂",
    messageToSelf: "Selalu ingat Allah dan jangan lupa kamu harus berhasil menyebarkan cinta ke dunia. 🤲🏻🤍"
  },
  {
    id: 16,
    name: "Khumairoh Bilqis Junaidi",
    nickname: "BJ",
    role: "Siswi Madrid",
    image: "16.jpg",
    traits: ["Senyum 😊", "Cermin 🪞", "Ramah 🤗"],
    hobbies: "Masak 🍳, nyanyi 🎶",
    favoriteFood: "Nasi goreng 🍳, semua makanan pedas 🌶️",
    favoriteSong: "It is You (Holic) 🎧",
    quote: "Try to be better than before. 🌱✨",
    messageToFriends: "Makasih udah buat hari-hari aku berwarna banget selama di PIAR. I miss u all! 🥺💖",
    hopeForClass: "Bahagia terus yaa, jaga kesehatan, jangan lupa kalo kita pernah sedekat itu. 🫂💫",
    messageToSelf: "Bismillah bisa jadi jaksa/hakim, tamat cumlaude, bahagiain orang tua. ⚖️🎓✨"
  },
  {
    id: 17,
    name: "Nadhira Rajwa El Rafi",
    nickname: "Nadhira",
    role: "Siswi Madrid",
    image: "17.jpg",
    traits: ["Suka chikeleta 🍫", "Ceria & Friendly 🥳", "Barang cute 🧸"],
    hobbies: "Baca buku 📚",
    favoriteFood: "Spaghetti 🍝",
    favoriteSong: "Brooklyn Baby - Lana Del Rey 🎧",
    quote: "We accept the love we think we deserve. 🤍✨",
    messageToFriends: "Semoga anak madrid bisa sukses di jalan yang udah kalian pilih. See u on top! 🎓🚀",
    hopeForClass: "Harapannya semoga kalian bisa sukses dan nikmatin kerja keras kalian selama ini. 🥂🌟",
    messageToSelf: "Kamu pasti udah gapai mimpi mu itu kan? Jangan lupa perjuangan kamu bertahun-tahun lalu. 🥺💖"
  },
  {
    id: 18,
    name: "Nafisah Faiza Farhani",
    nickname: "Picah",
    role: "Siswi Madrid",
    image: "18.jpg",
    traits: ["Imut 🤏🏻", "Lucu 🌸", "Menggemaskan 🥺"],
    hobbies: "Edit-edit video/foto 🎬, membaca 📖",
    favoriteFood: "Mochi! 🍡",
    favoriteSong: "Intro (End of the World) - Ariana Grande 🎧",
    quote: "Jangan pernah berprasangka buruk sama Allah SWT. 🤲🏻🤍",
    messageToFriends: "Semoga madrid sukses terus kedepannya dan tetap istiqomah di luar sana. ✨🤲🏻",
    hopeForClass: "Semoga kita tetap terjaga tali silaturahminya yaa. 🫂🤍",
    messageToSelf: "Kamu hebat, kamu kuat, kamu cantik imut dan kamu bisa jadi kebanggaan ortu. 🥹👑"
  },
  {
    id: 19,
    name: "Nasywa Talitha Herman",
    nickname: "Nasywa",
    role: "Siswi Madrid",
    image: "19.jpg",
    traits: ["Panikan 🫨", "Suka nyanyi 🎤", "Kacamata 👓"],
    hobbies: "Nyanyi 🎶",
    favoriteFood: "Nasi goreng 🍛, mie ayam PIAR 🍜",
    favoriteSong: "Amin Paling Serius 🎵",
    quote: "Hiduplah untuk dirimu sendiri, wishlistmu, mimpimu dan masa depanmu. 🌟📜",
    messageToFriends: "Semoga kedepannya kita bisa raih mimpi itu perlahan. Dijaga sholat & pakaiannya ya. 🤲🏻✨",
    hopeForClass: "Semangat untuk kedepannya, ditunggu kabar suksesnya. See u on top! 🚀🥳",
    messageToSelf: "Gagal bukan berarti gak sukses, gagal adalah awal dari perjalanan. 💪🏻💖"
  },
  {
    id: 20,
    name: "Naurah Amalia Syahidah",
    nickname: "k'Nau",
    role: "Siswi Madrid",
    image: "20.jpg",
    traits: ["Pemalu 🫣", "Soft spoken 🕊️", "Lucu 😊"],
    hobbies: "Banyak 🎨",
    favoriteFood: "Keju 🧀, manis-manis 🧁, tidak pedas 🙅🏻‍♀️",
    favoriteSong: "Banyak 🎧",
    quote: "Be kind, be grateful, and trust Allah timing. 🤲🏻✨",
    messageToFriends: "Terima kasih untuk semua teman-teman  yang sudah menjadi bagian dari perjalanan ini. Semoga kita semua diberikan kesehatan, kebahagiaan, dan kesuksesan dalam meraih cita-cita. Jangan lupakan  kenangan yang telah kita buat bersama ya, Semoga persahabatan dan silaturahmi kita tetap terjaga walaupun nanti berada di tempat yang berbeda. Sukses selalu untuk kita semua!🥹🫂",
    hopeForClass: "Semoga kita bisa bertemu dengan versi terbaik kita masing-masing. 🌟🤍",
    messageToSelf: "Semoga kamu bahagia,sehat dan menjadi pribadi yg lebih baik dari pada hari ini,jangan lupa untuk selalu bersyukur atas yg telah kamu dapatkan serta jangan pernah berhenti untuk berjuang ingat Allah selalu bersama  ,apapun yg terjadi padaku aku bangga pada diriku sendiri.🥺💖"
  },
  {
    id: 21,
    name: "Nayla Zuri",
    nickname: "Nazu",
    role: "Siswi Madrid",
    image: "21.jpg",
    traits: ["Cantik 🌸", "Tengil 😜", "Kiyowo 🥺"],
    hobbies: "Memasak 🧑🏻‍🍳",
    favoriteFood: "Ramen 🍜 & Pizza 🍕",
    favoriteSong: "Iqro - Raim Laode 🎧",
    quote: "Allah selalu bersama mu. 🤲🏻🤍",
    messageToFriends: "Jangan lupa sama teman-teman berjuang masa SMA ya. 🥹🤝🏻",
    hopeForClass: "Semoga kalian sehat terus dan jangan menyerah kalau ada masalah. 💪🏻💖",
    messageToSelf: "Jangan pantang menyerah dan terus berjuang berusaha selalu. 🔥✨"
  },
  {
    id: 22,
    name: "Nila Amalia Nabila",
    nickname: "Nila",
    role: "Siswi Madrid",
    image: "22.jpg",
    traits: ["Percaya diri 😎", "Ga bisa diam 🏃🏻‍♀️", "Lucu imut 🤏🏻"],
    hobbies: "Belajar 📚, cari teman baru 🤝🏻, ngomong 🗣️",
    favoriteFood: "Cumi 🦑, pempek 🐟",
    favoriteSong: "Lagu Rizky Febian, Tenxi & Nakyla 🎵",
    quote: "Kebahagiaan bermulai dari kenyamanan. 💖🍃",
    messageToFriends: "Anggota madrid bukan cuman teman, tapi keluarga yang tak tergantikan. 🥹🫂",
    hopeForClass: "Semoga madrid sukses hingga akhirat. 🤲🏻🌟",
    messageToSelf: "Kamu hebat loh udah bertahan dan berjuang sejauh ini. 🥺👏🏻"
  },
  {
    id: 23,
    name: "Nur Alifia Akhira",
    nickname: "Fifi",
    role: "Siswi Madrid",
    image: "23.jpg",
    traits: ["Cerewet 🗣️", "Ngambekan & Manja 🥺", "Suara cempreng 📢"],
    hobbies: "Membaca 📚, masak 🍳",
    favoriteFood: "Serba chiki 🍿",
    favoriteSong: "Bergema Sampai Selamanya 🎶",
    quote: "Ga suka kata-kata, sukanya bukti nyata. 🔥😎",
    messageToFriends: "Semoga anak madrid sukses terus, sehat terus, jgn lupain kita pernah bareng 3 tahun. 🥺💖",
    hopeForClass: "Nanti kedepannya kita dalam perjuangan masing-masing, jangan sampai asing yah. 🤝🏻🥹",
    messageToSelf: "Semoga aku lebih baik lagi kedepannya, apapun perjuangannya semoga Allah mudahkan. 🤲🏻✨"
  },
  {
    id: 24,
    name: "Nur Azizah",
    nickname: "Ajonk",
    role: "Siswi Madrid",
    image: "24.jpg",
    traits: ["Mudah senyum 😊", "Ambisius 🔥", "Ceria ☀️"],
    hobbies: "Nonton film 🎬, mendengarkan musik 🎧",
    favoriteFood: "Semua suka yang penting enak 😋",
    favoriteSong: "Slut! - Taylor Swift 🎶",
    quote: "Lelah itu wajar tapi, menyerah bukan pilihan. 💪🏻✨",
    messageToFriends: "Semoga kita selalu dekat sampai kapan pun, dan sukses mencapai impian masing-masing. 🫂🌟",
    hopeForClass: "Harapannya kita jangan ada yang melupakan satu sama lain, dan sukses! 🥹🥂",
    messageToSelf: "Ingat kembali masa-masa perjuangan ini, semua lelah adalah investasi masa depan. 🎓📜"
  },
  {
    id: 25,
    name: "Nurul Najmi A'isyah",
    nickname: "Nuna",
    role: "Siswi Madrid",
    image: "25.jpg",
    traits: ["Matematika 🔢", "Dance 💃🏻", "Novel 📚"],
    hobbies: "Dance 💃🏻, baca buku 📚",
    favoriteFood: "Mochi 🍡, jamur enoki 🍄",
    favoriteSong: "Shout Out 🎶, Joyride 🎵",
    quote: "Dan jika ia datang kepada-Ku dengan berjalan, Aku akan datang kepadanya dengan berlari. 🤲🏻🤍",
    messageToFriends: "Keep fighting teman-teman, sampai jumpa di puncak kesuksesan! 🚀🎓",
    hopeForClass: "Semoga beberapa tahun dari sekarang, kita semua berkumpul lagi sebagai orang sukses. 🥺🥂",
    messageToSelf: "Aku harap kamu sudah berdamai dengan semua kegagalan yang pernah membuat kamu menangis. 🫂🤍"
  },
  {
    id: 26,
    name: "Reva Mayanda",
    nickname: "Reva",
    role: "Siswi Madrid",
    image: "26.jpg",
    traits: ["Cantik 🌸", "Manis 🍬", "Lucu-lucu 😊"],
    hobbies: "Nonton 🍿",
    favoriteFood: "Ayam geprek 🍗, Dimsum mentai 🥟, Olahan pisang 🍌",
    favoriteSong: "Nothing Lasts Forever - Maroon 5 🎶",
    quote: "Love smiling, love laughing. 😊💖",
    messageToFriends: "Madrid selalu kerennnn, so glad to know them! 🥺✨",
    hopeForClass: "Dimanapun semuanya semoga selalu sukses. 🎓🌟",
    messageToSelf: "Jadi orang sukses dunia akhirat. 🤲🏻🤍"
  },
  {
    id: 27,
    name: "Rifa Ayuni Putri Dinata",
    nickname: "Ipak",
    role: "Siswi Madrid",
    image: "27.jpg",
    traits: ["Ceria ☀️", "Ramah 🤗", "Penyayang 💖"],
    hobbies: "Mendengarkan musik 🎧, kumpul keluarga 👨‍👩‍👧‍👧",
    favoriteFood: "Masakan mama 🥘",
    favoriteSong: "Love Me Not 🎵",
    quote: "Jangan pernah menyerah pada mimpi yang kamu miliki. 🌟🚀",
    messageToFriends: "Terima kasih sudah menjadi bagian dari perjalanan masa SMA yang indah. 🥺💖",
    hopeForClass: "Semoga Madrid selalu dikenang sebagai kelas yang kompak dan anggotanya sukses. 🤝🏻🎓",
    messageToSelf: "Semoga kamu sudah menjadi pribadi yang lebih kuat, bahagia, dan berhasil membanggakan keluarga. 🥹🤍"
  },
  {
    id: 28,
    name: "Sabita Izzati Aqila",
    nickname: "Bita",
    role: "Siswi Madrid",
    image: "28.jpg",
    traits: ["Cantik 🌸", "Manis 🍬", "Cerewet 🗣️"],
    hobbies: "Kerjain apa saja yang lagi disukai 🎨",
    favoriteFood: "Semua suka 😋",
    favoriteSong: "Lagu apa saja yang enak didengar 🎧",
    quote: "Apa yang tertakar tidak akan tertukar. 🍃✨",
    messageToFriends: "Makasih ya udah menemani hari-hari selama di PIAR. Maafin aku kalau bikin kalian kesal. 🥺💖",
    hopeForClass: "Madrid jadi orang sukses dunia akhirat, tercapai apa yang dicita-citakan. 🤲🏻🌟",
    messageToSelf: "Semoga tidak jadi orang yang menyepelekan hal-hal kecil dan selalu bersyukur. 🌱🤍"
  },
  {
    id: 29,
    name: "Siti Aisyah Humairoo",
    nickname: "Isyah",
    role: "Siswi Madrid",
    image: "29.jpg",
    traits: ["Gampang bosen 🥱", "Banyak ide 💡", "Moodyan 🎭"],
    hobbies: "Masak 🍳, jalan-jalan ✈️",
    favoriteFood: "Roti 🥖, dendeng lambok 🥩, dimsum 🥟",
    favoriteSong: "About You 🎧",
    quote: "Santri idaman anti maksiat gemar shalawat. 🤲🏻✨",
    messageToFriends: "Semoga kita bisa mencapai semua cita-cita yang udah kita gantung setingginya. 🚀🌟",
    hopeForClass: "Semoga kita bisa mencapai impian dan temenan sampe jadi nenek-nenek. 🥹👵🏻💖",
    messageToSelf: "Semoga Isyah tetap istiqamah dan disenangin orang sekitar. 🥺🤍"
  },
  {
    id: 30,
    name: "Ar. Syakiroh Khoitunnisa, S.Ars., M.Ars., Ph.D",
    nickname: "Syitoh",
    role: "Siswi Madrid",
    image: "30.jpg",
    traits: ["Kurus 🤏🏻", "Suka menggambar 🎨", "Suka marah 😡"],
    hobbies: "Belajar hal baru 📚",
    favoriteFood: "Es krim 🍦, siomay 🍢, bakso bakar 🍡",
    favoriteSong: "Ceritanya Jatuh Cinta - Aku Jeje 🎶",
    quote: "Study first, love will find you later. 🎓❤️",
    messageToFriends: "Jaga diri baik-baik ya semuanya. 🥺🤍",
    hopeForClass: "Semoga semuanya sukses dan dipermudah karirnya, aamiin. 🤲🏻💼",
    messageToSelf: "Jangan lupa sama Allah, kejar karir setinggi mungkin tapi tetap jadi orang bermanfaat. 🏛️🌟"
  },
  {
    id: 31,
    name: "Zakiah Salsabila",
    nickname: "Kiaa",
    role: "Siswi Madrid",
    image: "31.jpg",
    traits: ["Terorganisir 📋", "Math lover 🔢", "Adaptif 🌿"],
    hobbies: "Jalan-jalan 🚗, baca 📚, nonton 🎬",
    favoriteFood: "Martabak mesir 🥙",
    favoriteSong: "Everything You Are - Hindia 🎧",
    quote: "Tak apa ambil jeda, pun ini semua bukan perkara menang dan kalah. 🌿☕",
    messageToFriends: "Yang paling penting dimanapun tetap jaga sholatnya, jangan lupain kenangan madrid. 🥺🤲🏻",
    hopeForClass: "Tetap keep in touch semuanya, sukses di pilihan masing-masing. 🤝🏻🌟",
    messageToSelf: "Jangan biarkan ketakutan menghentikan mimpi, hargai setiap proses. 💪🏻💖"
  },
  {
    id: 32,
    name: "Zaskia Irna Dewantari",
    nickname: "Berbi",
    role: "Siswi Madrid",
    image: "32.jpg",
    traits: ["Cinta damai 🕊️", "Easy going 🍃", "Ramah 😊"],
    hobbies: "Menyanyi 🎤",
    favoriteFood: "Satee 🍡",
    favoriteSong: "Shape of My Heart 🎶",
    quote: "The beautiful thing about life is that you can always change, grow, and become better. 🌱✨",
    messageToFriends: "Tetap jadi diri sendiri ya guys, semangat untuk menjalani dunia perkuliahan. 🎓🚀",
    hopeForClass: "Harapannya semoga kita semua bisa sukses menggapai masa depannya masing-masing. 🥹🌟",
    messageToSelf: "Terimakasih untuk diriku yang sudah hebat melalui masa-masa yang tidak mudah. 🥺🫂"
  },
  {
    id: 33,
    name: "Zikra Aridiastuti",
    nickname: "Zizi",
    role: "Siswi Madrid",
    image: "33.jpg",
    traits: ["Girly abiz 👗", "Kecil mungil 🎀", "Cantik 🌸"],
    hobbies: "Baca novel 📖, nonton Barbie 👑, melukis 🎨, shopping 🛍️",
    favoriteFood: "Pie cheese 🧀, brownies 🥮, telur gulung 🍢",
    favoriteSong: "Thank U, Next - Ariana Grande 🎧",
    quote: "Be proud of yourself because you have survived a lot of things no one even noticed. 🥹💖",
    messageToFriends: "Semoga apapun yang kalian ucapin hari itu bisa bener-bener tercapai ya teman-temanku. 🤲🏻🌟",
    hopeForClass: "Madrid jangan asing yaa, jaga pertemanannya. Nanti kita ketemu lagi dengan versi terbaik. 🫂🥺",
    messageToSelf: "Dimana Zizi berada tetap jaga sholat dan amalan ibadahnya. Jadi orang baik ya Zi. 🤍🤲🏻"
  }
];
