const studentsData = [
  {
    id: 1,
    name: "Edriani, M.Pd",
    nickname: "Zah Eed",
    type: "teacher",
    role: "Wali Kelas X Sofia (2023/2024) & XI Latvia (2024/2025)",
    image: "https://lh3.googleusercontent.com/d/1N3IU7XweiOMZdMOdUb5sXIEG5hwPPrPx",
    traits: ["Penyabar", "Pengayom", "Dedikatif"],
    hobby: "-",
    favFood: "-",
    favSong: "-",
    quote: "-",
    impression: "-",
    messageForClass: "-",
    futureHope: "-"
  },
  {
    id: 2,
    name: "Putri Handayani, S.Pd",
    nickname: "Zah Iput",
    type: "teacher",
    role: "Wali Kelas XII.4 Madrid (2025/2026)",
    image: "https://lh3.googleusercontent.com/d/1y7VytDPBSTpzg5Mk6EWFKZ9G_WjS2A4E",
    traits: ["Perhatian", "Hangat", "Penyabar"],
    hobby: "-",
    favFood: "-",
    favSong: "-",
    quote: "Madrid zahhh, she is my girl, always.",
    impression: "Rusuh, heboh, gabisa diem kecuali saat tidur. Keliatan cuek dari luar, tapi hangat dari dalam.",
    messageForClass: "Jaga kesehatan ya girls. Minimal salat lima waktu ga tinggal, jilbab ga copot, tilawah juga.",
    futureHope: "See u on top Madrid. Sazah berharap kalau terpuruk/sedih, sazah masih jadi salah satu tempat cerita."
  },
  {
    id: 3,
    name: "Afifah Nurul Izzah",
    nickname: "Ipeh",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/19Y9lBacQ6RtmZCthTwgE5CfilE4OqWuX",
    traits: ["Manja", "Penyabar", "Introvert"],
    hobby: "Dengerin lagu, nonton, baca buku",
    favFood: "Ayam",
    favSong: "Risk It All",
    quote: "Fall seven times, stand up eight.",
    impression: "3 tahun di Madrid berkesan banget dari yang gak dekat sampai sedekat ini.",
    messageForClass: "Semoga kita sukses selalu dikemudian hari dan jangan tinggal sholatnya yaaa.",
    futureHope: "Sukses selalu Madrid dunia dan akhiratnyaa!"
  },
  {
    id: 4,
    name: "Afifah Thohiroh Muthmainnah",
    nickname: "ATM",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1h54Cp1mvpoxSOegRFVaxihnNq9GoXNAa",
    traits: ["Ceria", "Baik"],
    hobby: "Jalan-jalan, baca novel",
    favFood: "Soto ayam, prata, ayam geprek",
    favSong: "Wavin' Flag, Kita Usahakan Rumah Itu",
    quote: "Orang-orang besar itu terlahir dari masalah yang besar juga.",
    impression: "Seneng banget dapet orang-orang Madrid, walas support & kawan selalu ada.",
    messageForClass: "Terima kasih ke diri sendiri karena udah berjuang sekeras ini. Nikmati prosesnya.",
    futureHope: "Sukses selalu ya Madrid, jangan asing satu sama lain yaa."
  },
  {
    id: 5,
    name: "Aisyah Azzahra Fikria Imam",
    nickname: "Icaza",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1hokFI5q9yLpOFJ5Z5R0eg5p5Trp3bpLa",
    traits: ["Excited", "Berani", "Aneh/Frik"],
    hobby: "Nyanyi, main FF, makan, baca",
    favFood: "Cokelat manis",
    favSong: "Dash Uchiha",
    quote: "Kalo gabisa jadi orang baik, setidaknya jangan jadi orang jahat.",
    impression: "Selama 3 tahun lucu bgt kita. Kalo bisa nambah waktu aku mau 100 tahun lagi di Madrid!",
    messageForClass: "Sejauh apapun besok dunia luar membawa kita, jgn pernah lupa kita pernah sedekat itu.",
    futureHope: "Semoga kita semua bisa jadi orang baik dan sukses."
  },
  {
    id: 6,
    name: "Alya Malika Wirahadi",
    nickname: "Malik",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1Ja-7JHbS94bntby-I9vG32rnWasQYyuV",
    traits: ["Baik", "Penyayang", "Softspoken"],
    hobby: "Jalan-jalan",
    favFood: "Mie",
    favSong: "Banyak",
    quote: "Tetaplah menjadi dirimu dan hargai orang yang menghargaimu.",
    impression: "Madrid udah seperti rumah dan keluarga kedua aku.",
    messageForClass: "Bagaimanapun dan dimanapun nanti kita berada semoga kita tak akan pernah lupa satu sama lain.",
    futureHope: "Semoga kita menjadi manusia hebat di masa depan."
  },
  {
    id: 7,
    name: "Amaliya Palupi Hardian",
    nickname: "Amal",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1vhAx1X45-5xzKv12wVjfkwBnNihEOEwj",
    traits: ["Ngangenin", "Ngeselin", "Dramatic"],
    hobby: "Nonton",
    favFood: "Cheesecake",
    favSong: "Drop Dead / Wish List",
    quote: "Our future is up to us.",
    impression: "Madrid se-membekas itu di hati aku, 3 tahun paling berharga.",
    messageForClass: "Semoga kita bisa ketemu lagi di best version kita yahh.",
    futureHope: "I hope Madrid sukseees dan tercapai smuwa wish listnyaa."
  },
  {
    id: 8,
    name: "Atikah Istiqamah",
    nickname: "Qomah",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1vJJWSJ5CZFMwvCSKCS5DS58p37WGUXcT",
    traits: ["Periang", "Cekatan", "Fleksibel"],
    hobby: "Basket, sepedaan",
    favFood: "Mie ayam",
    favSong: "They Said Only a Dignified Life",
    quote: "Allah bersamaku, Allah melihatku, Allah menyaksikanku.",
    impression: "Makan bajambaa, main basket sekelas, saling care waktu sakit.",
    messageForClass: "Perbaiki niat kalian ya, semoga kita berjumpa di surga nantiii.",
    futureHope: "Semoga kita jadi orang sukses versi masing-masing."
  },
  {
    id: 9,
    name: "Azkiah Mutia Najla",
    nickname: "Amoy",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1FjS8WRWJo5lDyssn2ZQiV1nrDRZ4_PIw",
    traits: ["Lucu", "Imut", "Menggemaskan"],
    hobby: "Tidur, baca buku",
    favFood: "Bakso, kuaci",
    favSong: "Bayangkan Jika Kita Tidak Menyerah",
    quote: "Be happy not because everything is good, but you can see good in everything.",
    impression: "Madrid isinya orang-orang yang punya mimpi besar dan mau memperjuangkannya.",
    messageForClass: "Let's strive to be the best versions of ourselves.",
    futureHope: "Semoga suatu saat kita bisa bertemu dan cerita mimpi kita udah terwujud."
  },
  {
    id: 10,
    name: "Callysta Aura Az Zahra",
    nickname: "Celis",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1gPjtqQXDqTCaJkHMTOyD7H0_i4HbRZlt",
    traits: ["Sabar", "Tidak sombong", "Cakep"],
    hobby: "Berenang",
    favFood: "Pempek",
    favSong: "Dandelions",
    quote: "QS. Al-Insyirah 5-6",
    impression: "Sangat amat kompak, anak-anaknya baik dan kerja sama mantap.",
    messageForClass: "Semoga bisa menempuh masa depan yang diimpikan.",
    futureHope: "Semoga Madrid ga asing ya."
  },
  {
    id: 11,
    name: "Claudya Annisa",
    nickname: "Kolok",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1B9xR8HaQNds3PpiFWMsummJMe2D8J2a0",
    traits: ["Gemoy", "Cerewet", "Selalu bahagia"],
    hobby: "Memasak, merakit lego",
    favFood: "Basreng, dendeng lambok",
    favSong: "Tarot, End of Beginning",
    quote: "Abandon thoughts that make you weak.",
    impression: "Bangga punya temen kelas kyk Madrid, selalu support pas lagi down.",
    messageForClass: "Walaupun kita udh pada pisah tapi tetap jangan asing ya guys.",
    futureHope: "Mudah-mudahan kita sukses selalu di masa depan."
  },
  {
    id: 12,
    name: "Diana Intan Putri",
    nickname: "Diana",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1hMRaZEDEzoCbGlGoPcLgpTvt5_6o7PP2",
    traits: ["Alistabaa", "Suara emas", "Enjiner idaman"],
    hobby: "Main game, masak",
    favFood: "Martabak manis, bolu pisang",
    favSong: "Jatuh Suka, Lantas, Titik Nadir",
    quote: "Life is what happens while you're busy making other plans.",
    impression: "Happy jadi bagian Madrid 3 tahun ini. Kangen main mafia & nobar The Glory.",
    messageForClass: "Yakin seyakin-yakinnya kita bakalan sukses di masa depan.",
    futureHope: "Sukses selalu Madridku!"
  },
  {
    id: 13,
    name: "Fadhilah Zahrah",
    nickname: "Ara",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1OkNfwvT46P55Rf58kCqD5roAmT9N5jeR",
    traits: ["Public speaking", "Tegas", "Kepoan"],
    hobby: "Dengerin musik",
    favFood: "Desserts, ketoprak, siomay",
    favSong: "Lagu Sheila On 7 & Armada",
    quote: "You cry, you pray, you wait.",
    impression: "Semua dari Sofia sampai Madrid berkesan: display kelas, makan, nonton, main remi.",
    messageForClass: "Tolong ingat Ara yang baiknya aja ya teman-teman. Love u guys.",
    futureHope: "Semoga kalian diberikan kebahagiaan dan kesuksesan."
  },
  {
    id: 14,
    name: "Fauzatul Husna",
    nickname: "Aza",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1rwrD_3riFMpoulBjFb9hpkahE2yRZBYt",
    traits: ["Ekspresif", "Perasa", "Fleksibel"],
    hobby: "Menggambar, musik, baca manhwa",
    favFood: "Aci-acian, soup, cheesecake",
    favSong: "The Cutest Pair, Bunga Abadi",
    quote: "I survived every day I thought I couldn't.",
    impression: "Madrid tuh isinya rame, kreatif, unik. Kadang berisik tapi ngangenin.",
    messageForClass: "Makasih udah jadi bagian dari masa SMA yang bakal selalu aku kenang.",
    futureHope: "Don't forget to stay istiqomah and keep Allah at the center."
  },
  {
    id: 15,
    name: "Haura Ulya Ramadhani",
    nickname: "Haura",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1LBiENtKgSzhAX1jedlQQT90-Y050YYpp",
    traits: ["Suka warna-warni", "Ceria"],
    hobby: "Nyanyi, jalan-jalan, jajan",
    favFood: "Suka semuanya",
    favSong: "Saving All My Love For You",
    quote: "See beauty in everything, lessons in every hardship.",
    impression: "Pengalamannya banyak dari menyenangkan sampai luar biasa. Lucky ketemu kalian.",
    messageForClass: "Makasii buat semua kenangan dan pelajarannya. See u on the top!",
    futureHope: "Semoga kita bisa bersyukur dan bangga sama capaian kita."
  },
  {
    id: 16,
    name: "Khumairoh Bilqis Junaidi",
    nickname: "BJ",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1bAL_hfN4N0prjgeQy6QQbhpVKKhLyfh2",
    traits: ["Penyenyum", "Friendly", "Ramah"],
    hobby: "Masak, nyanyi",
    favFood: "Nasi goreng, makanan pedas",
    favSong: "It's You (Holic)",
    quote: "Try to be better than before.",
    impression: "Beruntung banget bisa jadi bagian dari kelas Madrid. Kompak & susah senang sama-sama.",
    messageForClass: "Makasih banyak buat 3 tahunnya. Maafin kalo ada salah.",
    futureHope: "Bahagia terus yaaa, jangan lupa kalo kita pernah sedekat itu."
  },
  {
    id: 17,
    name: "Nadhira Rajwa El Rafi",
    nickname: "Nadhira",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1xlLFeT1oH0aR2EzKiscpAD2fguvrV7Ok",
    traits: ["Friendly", "Ceria", "Suka barang cute"],
    hobby: "Baca buku",
    favFood: "Spaghetti",
    favSong: "Brooklyn Baby - Lana Del Rey",
    quote: "We accept the love we think we deserve.",
    impression: "Madrid banyak ngasih momen susah dilupain kayak nobar & bikin tugas.",
    messageForClass: "Semoga anak Madrid bisa sukses di jalan yang kalian pilih.",
    futureHope: "Semoga kalian bisa sukses dan jadi orang-orang keren kebanggaan."
  },
  {
    id: 18,
    name: "Nafisah Faiza Farhani",
    nickname: "Picah",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1bzrwl-k4YVLBQo5mUt8ijvmYxfXhH6ch",
    traits: ["Imut", "Lucu", "Menggemaskan"],
    hobby: "Editing, membaca",
    favFood: "Mochi!",
    favSong: "Intro (End of the World)",
    quote: "Jangan pernah berprasangka buruk sama Allah SWT.",
    impression: "Seru sih Madrid tu, terus juga kompak bgt!",
    messageForClass: "Semoga Madrid sukses terus kedepannya dan tetap istiqomah.",
    futureHope: "Semoga kita tetap terjaga tali silaturahminya yaa."
  },
  {
    id: 19,
    name: "Nasywa Talitha Herman",
    nickname: "Nasywa",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1pGUSwqy-Obs6jPe8E_Oju_mIYu9mur3U",
    traits: ["Panikan", "Suka nyanyi", "Kacamata"],
    hobby: "Nyanyi",
    favFood: "Nasi goreng, mie ayam PIAR",
    favSong: "Amin Paling Serius",
    quote: "Hiduplah untuk dirimu sendiri, wishlistmu, mimpimu.",
    impression: "Senang sekali bisa bertemu dengan kalian semua.",
    messageForClass: "Jangan lupa murajaah, shalat, dan pakaian dijaga.",
    futureHope: "Semangat untuk kedepannya, ditunggu kabar suksesnya. See u on top!"
  },
  {
    id: 20,
    name: "Naurah Amalia Syahidah",
    nickname: "k’Nau",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1y8XH7bmw62GllWo2fR5Th5KUysxyll-6",
    traits: ["Pemalu", "Soft spoken", "Lucu"],
    hobby: "Membaca & menggambar",
    favFood: "Keju, manis-manis",
    favSong: "Banyak",
    quote: "Be kind, be grateful, and trust Allah's timing.",
    impression: "Semua keseruan dan cerita di Madrid, apalagi sifat random kalian.",
    messageForClass: "Terima kasih sudah menjadi bagian dari perjalanan ini. Jangan lupakan kenangan kita.",
    futureHope: "Semoga kita bisa bertemu dengan versi terbaik kita masing-masing."
  },
  {
    id: 21,
    name: "Nayla Zuri",
    nickname: "Nazu",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1C81Aj2TNx9FY-dFEHIf_949N02mRg7Ty",
    traits: ["Cantik", "Tengil", "Kiyowo"],
    hobby: "Memasak",
    favFood: "Ramen and Pizza",
    favSong: "Iqro - Raim Laode",
    quote: "Allah selalu bersamamu.",
    impression: "Semua hal yang kita lakukan berkesan semua siee kata aku.",
    messageForClass: "Jangan lupa sama teman-teman berjuang masa SMA ya.",
    futureHope: "Semoga kalian sehat terus dan jangan menyerah kalau ada masalah."
  },
  {
    id: 22,
    name: "Nila Amalia Nabila",
    nickname: "Nila",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1HZ5W-rtpxmBCDrYixoiEjQPyulX0ykHf",
    traits: ["Percaya diri", "Ga bisa diam", "Lucu imut"],
    hobby: "Belajar, ngomong",
    favFood: "Cumi, pempek",
    favSong: "Lagu Rizky Febian",
    quote: "Kebahagiaan bermulai dari kenyamanan.",
    impression: "Semuanya kesan yang indah sampai lupa rasa sakit selama SMA.",
    messageForClass: "Anggota Madrid bukan cuma teman, tapi keluarga tak tergantikan.",
    futureHope: "Semoga Madrid sukses hingga akhirat."
  },
  {
    id: 23,
    name: "Nur Alifia Akhira",
    nickname: "Fifi",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SIO8UHAzFItzpnWhKhXgRzsW4G7FGET5",
    traits: ["Cerewet", "Manja", "Suara cempreng"],
    hobby: "Membaca, masak",
    favFood: "Serba chiki",
    favSong: "Bergema Sampai Selamanya",
    quote: "Ga suka kata-kata, sukanya bukti nyata.",
    impression: "Madrid isinya orang spesial semua, kerandomannya bikin gamon bgt!",
    messageForClass: "Semoga anak Madrid sukses terus dan sehat terus.",
    futureHope: "Nanti kedepannya kita dah dalam perjuangan masing-masing, jangan asing yah."
  },
  {
    id: 24,
    name: "Nur Azizahh",
    nickname: "Ajonk",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1lHTqPpYE3h-j1QhbGktRD5NpLwlR2HbI",
    traits: ["Mudah senyum", "Ambisius", "Ceria"],
    hobby: "Nonton film, mendengarkan musik",
    favFood: "Semua yang enak",
    favSong: "Slut! - Taylor Swift",
    quote: "Lelah itu wajar, tapi menyerah bukan pilihan.",
    impression: "Madrid bagi aku benar-benar kayak keluarga. Senang sedih sama-sama.",
    messageForClass: "Semoga kita selalu dekat sampai kapan pun dan sukses menggapai impian.",
    futureHope: "Harapannya kita jangan ada yang melupakan satu sama lain."
  },
  {
    id: 25,
    name: "Nurul Najmi A'isyah",
    nickname: "Nuna",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1JZLYbLAUZSTqWOrtsJiQUMlRfYNC3V2Z",
    traits: ["Matematika", "Dance", "Novel"],
    hobby: "Dance, baca buku",
    favFood: "Mochi, jamur enoki",
    favSong: "Shout Out, Joyride",
    quote: "Dan jika ia datang kepada-Ku dengan berjalan, Aku akan datang dengan berlari.",
    impression: "Pengalaman paling berkesan pas kelas tiga ngerayain ultah Zah Iput.",
    messageForClass: "Keep fighting teman-teman! Langkah boleh beda tapi kenangan tetap sama.",
    futureFuture: "Buktikan kelas kita melahirkan orang-orang hebat!"
  },
  {
    id: 26,
    name: "Reva Mayanda",
    nickname: "Reva",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1Qxr_AgKvuV1rujYDPOGzGTnikN4lqqUx",
    traits: ["Cantik", "Manis", "Lucu"],
    hobby: "Nonton",
    favFood: "Ayam geprek, dimsum mentai",
    favSong: "Nothing Lasts Forever",
    quote: "Love smiling, love laughing.",
    impression: "Nonton terusss pas di Sofia, momen kebersamaan yang tak terganti.",
    messageForClass: "Madrid selalu kerennnn, so glad to know them!",
    futureHope: "Dimanapun semuanya semoga selalu sukses."
  },
  {
    id: 27,
    name: "Rifa Ayuni Putri Dinata",
    nickname: "Ipak",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1yo1CZhIo_VCQCiOcvXq7xHUQbhpC8Eqb",
    traits: ["Ceria", "Ramah", "Penyayang"],
    hobby: "Mendengarkan musik",
    favFood: "Masakan mama",
    favSong: "Love Me Not",
    quote: "Jangan pernah menyerah pada mimpi yang kamu miliki.",
    impression: "3 tahun bersama Madrid dapat kenangan yang tidak akan terlupakan.",
    messageForClass: "Terima kasih sudah menjadi bagian dari perjalanan SMA yang indah.",
    futureHope: "Semoga Madrid selalu dikenang sebagai kelas yang kompak dan sukses."
  },
  {
    id: 28,
    name: "Sabita Izzati Aqila",
    nickname: "Bita",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1Ix-92lpt2hwnSmDUP5QSzGBcrSJUOTEw",
    traits: ["Cantik", "Manis", "Cerewet"],
    hobby: "Melakukan hal disukai",
    favFood: "Semua suka",
    favSong: "Lagu enak didengar",
    quote: "Apa yang tertakar tidak akan tertukar.",
    impression: "Tiap hari berkesan! Kunjed ketinggalan bus, surprise walas, masak randang.",
    messageForClass: "Makasi udah menemani hari-hari di PIAR. Lov u so much Madrid 26!",
    futureHope: "Madrid jadi orang sukses dunia akhirat. Ngumpul tiap tahun!"
  },
  {
    id: 29,
    name: "Siti Aisyah Humairoo",
    nickname: "Isyah",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1kbNjUiEexj1FYeDDVCKiitWqK2buIvhC",
    traits: ["Kreatif", "Banyak ide", "Moodyan"],
    hobby: "Masak, jalan-jalan",
    favFood: "Roti, dendeng lambok",
    favSong: "About You",
    quote: "Santri idaman anti maksiat gemar shalawat.",
    impression: "Bersyukur dapet kelas super kompak & dapet nilai rata-rata tertinggi se-IPA!",
    messageForClass: "Semoga kita bisa mencapai semua cita yang udah kita gantung setingginya.",
    futureHope: "Semoga kita temenan sampe jadi nenek-nenek punya cucu yang imut."
  },
  {
    id: 30,
    name: "Syakiroh Khoitunnisa",
    nickname: "Syakiroh",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1eVPsMZzPtulOXBZMvHlRWFazdhtrlkSa",
    traits: ["Kurus", "Suka menggambar", "Tegas"],
    hobby: "Belajar hal baru",
    favFood: "Es krim, siomay, bakso bakar",
    favSong: "Ceritanya Jatuh Cinta",
    quote: "Study first, love will find you later.",
    impression: "Madrid tu kelasnya hangat banget.",
    messageForClass: "Jaga diri baik-baik ya semuanya.",
    futureHope: "Semoga semuanya sukses dan dipermudah karirnya, aamiin."
  },
  {
    id: 31,
    name: "Zakiah Salsabila",
    nickname: "Kiaa",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1VYsDAHgC5xH3JLHgcDEn9GW1wzbvv0bQ",
    traits: ["Terorganisir", "Math lover", "Adaptif"],
    hobby: "Jalan-jalan, baca, nonton",
    favFood: "Martabak mesir",
    favSong: "Everything You Are - Hindia",
    quote: "Tak apa ambil jeda, pun ini semua bukan perkara menang dan kalah.",
    impression: "Madrid isinya heboh-heboh, saling support, dan suka ramein perpus.",
    messageForClass: "Yang paling penting dimanapun tetap jaga sholatnya ya.",
    futureHope: "Tetap keep in touch semuanya, sukses di pilihan masing-masing."
  },
  {
    id: 32,
    name: "Zaskia Irna Dewantari",
    nickname: "Berbi",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/13-uRhJJJLWXLBhBIZ59Fkv_wQIzpvH3J",
    traits: ["Cinta damai", "Easy going", "Ramah"],
    hobby: "Menyanyi",
    favFood: "Satai",
    favSong: "Shape of My Heart",
    quote: "The beautiful thing about life is that you can always change and grow.",
    impression: "Bisa sekelas dengan orang-orang random, pinter, dan ambis kayak kalian.",
    messageForClass: "Tetap jadi diri sendiri ya guys, jangan lupakan kebersamaan kita.",
    futureHope: "Harapannya semoga kita semua bisa sukses menggapai masa depan."
  },
  {
    id: 33,
    name: "Zikra Aridiastuti",
    nickname: "Zizi",
    type: "student",
    image: "https://lh3.googleusercontent.com/d/1SdeW0aKxjBJa20bwFqg5Q_GTVM9qbEeI",
    traits: ["Girly", "Mungil", "Cantik"],
    hobby: "Membaca novel, melukis, shopping",
    favFood: "Pie cheese, brownies, telur gulung",
    favSong: "Thank U, Next - Ariana Grande",
    quote: "Be proud of yourself because you have survived a lot of things.",
    impression: "Serunya nobar sekelas diem-diem dan out of the box bgt kesehariannya.",
    messageForClass: "Semoga apapun harapan kalian bener-bener bisa tercapai yaa.",
    futureHope: "Madrid jangan asing yaa, kita ketemu lagi pas udah sama-sama sukses!"
  }
];
